# Generated by Django 2.2.3 on 2019-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_pessoa_biografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nome da Ideia')),
                ('descricao', models.TextField(verbose_name='Descreva a sua ideia')),
                ('categorias', models.CharField(choices=[('TERRA_PLANA', 'Terra Plana'), ('COACHINTERIA', 'Ideia de Coach'), ('CONTRA_JOAO', 'Ideia contra o João'), ('PUBLICAS', 'Publicas'), ('OUTROS', 'Outros')], max_length=255, verbose_name='Categorias')),
                ('categoria_outros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caso outros, qual?')),
                ('pessoa', models.ForeignKey(on_delete=None, to='website.Pessoa')),
            ],
        ),
    ]
