# Generated by Django 2.2.3 on 2019-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=255, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nome da Ideia')),
                ('descricao', models.TextField(verbose_name='Descreva a sua ideia')),
                ('categoria', models.CharField(choices=[('TERRA_PLANA', 'Terra Plana'), ('COACHINTERIA', 'Ideia de Coach'), ('CONTRA_JOAO', 'Ideia contra o João'), ('PUBLICAS', 'Publicas'), ('OUTROS', 'Outros')], max_length=255, verbose_name='Categorias')),
                ('categoria_outros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caso outros, qual?')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_de_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(on_delete=None, to='website.Pessoa')),
            ],
        ),
    ]
